export interface ResumeDesign {
  template: string;
  primaryColor: string;
  secondaryColor: string;
  background: string;
  fontHeading: string;
  fontBody: string;
  fontSize: number;
  headingSize: number;
  lineHeight: number;
  pageMargin: number;
  marginTop?: number;
  marginBottom?: number;
  marginLeft?: number;
  marginRight?: number;
  sectionSpacing: number;
  paragraphSpacing: number;
  bulletSpacing: number;
  lengthTarget?: 'auto' | '1-page' | '2-page';
  enableAutoFit?: boolean;
  autoFitMode?: 'strict' | 'preferred';
  spacing?: 'compact' | 'normal' | 'relaxed';
  layout: string;
  headerStyle: string;
  photoShape: string;
  iconStyle: string;
  dividerStyle: string;
  borderRadius: number;
  density: 'compact' | 'comfortable' | 'loose';
  paperSize: string;
  accentColor?: string;
  showPageNumbers?: boolean;
  headingColor?: string;
  bodyTextColor?: string;
  linkColor?: string;
  dividerColor?: string;
  sidebarColor?: string;
  skillChipColor?: string;
  timelineColor?: string;
  bulletColor?: string;
  sectionLabelColor?: string;
  fontName?: string;
  bodySize?: number;
  sectionSize?: number;
  nameSize?: number;
  letterSpacing?: number;
  wordSpacing?: number;
  fontWeight?: string;
  textTransformHeading?: string;
  fontStyleHeading?: string;
  textTransformName?: string;
  visibleSections?: {
    summary?: boolean;
    experience?: boolean;
    education?: boolean;
    skills?: boolean;
    projects?: boolean;
    certifications?: boolean;
    achievements?: boolean;
    references?: boolean;
    languages?: boolean;
  };
}
